# Generated by Django 4.0.4 on 2022-04-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_alter_equipo_bandera_alter_equipo_escudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre del Equipo'),
        ),
        migrations.AlterField(
            model_name='historicalequipo',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nombre del Equipo'),
        ),
    ]
