# Generated by Django 4.0.4 on 2022-04-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljugador',
            name='foto',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto del jugador'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto del jugador'),
        ),
    ]
